# These are supported funding model platforms

github: [lZiMUl] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: lZiMUl # Replace with a single Patreon username
open_collective: lZiMUl # Replace with a single Open Collective username
ko_fi: lZiMUl # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Law Assist Adventure # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: lZiMUl # Replace with a single Liberapay username
issuehunt: lZiMUl # Replace with a single IssueHunt username
lfx_crowdfunding: lZiMUl # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: lZiMUl # Replace with a single Polar username
buy_me_a_coffee: lZiMUl # Replace with a single Buy Me a Coffee username
custom: ['https://www.paypal.me/lzimul'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
