name: Release with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.4.0
      with:
        version-source: file
        version-file: gradle.properties
        version-file-extraction-pattern: '(?<=mod_version=).+'

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod 777 ./gradlew

    - name: Build with gradle
      run: ./gradlew build --info

    - name: Publish gitHub release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.ACCESS_TOKEN }}"
        automatic_release_tag: "v${{ env.CURRENT_VERSION }}"
        title: "Law Assist Adventure ${{ env.CURRENT_VERSION }}"
        prerelease: false
        files: ./build/libs/law_assist_adventure-${{ env.CURRENT_VERSION }}.jar


  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3.1.0
